/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface FontAwesome {
        "iconClass": string;
    }
    interface InputFormLogin {
        "icon": string;
        "inputTitle": string;
        "two": boolean;
        "type": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLFontAwesomeElement extends Components.FontAwesome, HTMLStencilElement {
    }
    var HTMLFontAwesomeElement: {
        prototype: HTMLFontAwesomeElement;
        new (): HTMLFontAwesomeElement;
    };
    interface HTMLInputFormLoginElement extends Components.InputFormLogin, HTMLStencilElement {
    }
    var HTMLInputFormLoginElement: {
        prototype: HTMLInputFormLoginElement;
        new (): HTMLInputFormLoginElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "font-awesome": HTMLFontAwesomeElement;
        "input-form-login": HTMLInputFormLoginElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface FontAwesome {
        "iconClass"?: string;
    }
    interface InputFormLogin {
        "icon"?: string;
        "inputTitle"?: string;
        "two"?: boolean;
        "type"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "font-awesome": FontAwesome;
        "input-form-login": InputFormLogin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "font-awesome": LocalJSX.FontAwesome & JSXBase.HTMLAttributes<HTMLFontAwesomeElement>;
            "input-form-login": LocalJSX.InputFormLogin & JSXBase.HTMLAttributes<HTMLInputFormLoginElement>;
        }
    }
}
